site_name: Laravel JSON API
site_description: JSON API (jsonapi.org) support for Laravel applications.
site_author: Cloud Creativity Ltd
repo_url: https://github.com/cloudcreativity/laravel-json-api
theme: readthedocs

pages:
  - Home: index.md
  - Installation: installation.md
  - Upgrading: upgrade.md
  - The Basics:
    - APIs: basics/api.md
    - Routing: basics/routing.md
    - Controllers: basics/controllers.md
    - Adapters: basics/adapters.md
    - Schemas: basics/schemas.md
    - Validation: basics/validators.md
    - Security: basics/security.md
    - Testing: basics/testing.md
  - Fetching Data:
    - Fetching Resources: fetching/resources.md
    - Fetching Relationships: fetching/relationships.md
    - Inclusion of Related Resources: fetching/inclusion.md
    - Sparse Fieldsets: fetching/sparse-fieldsets.md
    - Sorting: fetching/sorting.md
    - Pagination: fetching/pagination.md
    - Filtering: fetching/filtering.md
  - Creating, Updating and Deleting:
    - Creating Resources: crud/creating.md
    - Updating Resources: crud/updating.md
    - Updating Relationships: crud/relationships.md
    - Deleting Resources: crud/deleting.md
  - Digging Deeper:
    - Asynchronous Processing: features/async.md
    - Broadcasting: features/broadcasting.md
    - Errors: features/errors.md
    - Helpers: features/helpers.md
    - HTTP Clients: features/http-clients.md
    - Localization: features/localization.md
    - Media Types: features/media-types.md
    - Packages: features/packages.md
    - Resolvers: features/resolvers.md
    - Responses: features/responses.md
    - Soft-Deting: features/soft-deletes.md
    - Views: features/views.md
